# Generated by Django 5.2.16 on 2026-08-01 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_equipment_history', to='equipment.equipmentcomponent', verbose_name='Componente del catálogo'),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_item_history', to='equipment.equipment', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items_installed', to=settings.AUTH_USER_MODEL, verbose_name='Instalado por'),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='previous_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_records', to='services.equipmentinstalleditem', verbose_name='Instalación anterior'),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='source_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donated_installed_items', to='equipment.equipment', verbose_name='Equipo de procedencia'),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceassignmenthistory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceassignmenthistory',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_assignment_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceassignmenthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceassignmenthistory',
            name='new_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_service_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceassignmenthistory',
            name='previous_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_service_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceassignmenthistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicechecklist',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicechecklist',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_checklists_completed', to=settings.AUTH_USER_MODEL, verbose_name='Completado por'),
        ),
        migrations.AddField(
            model_name='servicechecklist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicechecklist',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_checklists_started', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por'),
        ),
        migrations.AddField(
            model_name='servicechecklist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicechecklistitem',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicechecklistitem',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_checklist_items_checked', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='servicechecklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.servicechecklist', verbose_name='Checklist'),
        ),
        migrations.AddField(
            model_name='servicechecklistitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicechecklistitem',
            name='source_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_checklist_items', to='equipment.equipmentcomponent', verbose_name='Componente del catálogo'),
        ),
        migrations.AddField(
            model_name='servicechecklistitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceevidence',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceevidence',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_evidences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceevidence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceevidence',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstallationitem',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstallationitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstallationitem',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_installation_items_installed', to=settings.AUTH_USER_MODEL, verbose_name='Técnico instalador'),
        ),
        migrations.AddField(
            model_name='serviceinstallationitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='installation_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installed_item_history', to='services.serviceinstallationitem', verbose_name='Ítem de instalación'),
        ),
        migrations.AddField(
            model_name='servicemeterreading',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicemeterreading',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicemeterreading',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsable'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='equipment.equipment', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicemeterreading',
            name='service_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading', to='services.serviceorder'),
        ),
        migrations.AddField(
            model_name='serviceinstallationitem',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installation_items', to='services.serviceorder', verbose_name='OS de instalación'),
        ),
        migrations.AddField(
            model_name='serviceevidence',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='services.serviceorder'),
        ),
        migrations.AddField(
            model_name='servicechecklist',
            name='service_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='services.serviceorder', verbose_name='Orden de servicio'),
        ),
        migrations.AddField(
            model_name='serviceassignmenthistory',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='services.serviceorder'),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_item_history', to='services.serviceorder', verbose_name='OS de instalación'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='current_responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_service_part_requests', to=settings.AUTH_USER_MODEL, verbose_name='Responsable actual'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='installation_service_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_part_request', to='services.serviceorder', verbose_name='OS de instalación'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='logistics_prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_requests_logistics_prepared', to=settings.AUTH_USER_MODEL, verbose_name='Preparado por logística'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='management_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_requests_management_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por gerencia'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='service_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='part_request', to='services.serviceorder', verbose_name='OS de origen'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='stock_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_requests_stock_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Stock revisado por'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_requests_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='servicepartrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='part_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_item_history', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestattachment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestattachment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestattachment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_request_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='servicepartrequestcomment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_request_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='servicepartrequestcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestcomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_service_part_request_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios mencionados'),
        ),
        migrations.AddField(
            model_name='servicepartrequestcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='services.servicepartrequestcomment', verbose_name='Comentario respondido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestcomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestcomment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestdecision',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestdecision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestdecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_request_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por'),
        ),
        migrations.AddField(
            model_name='servicepartrequestdecision',
            name='previous_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassessments', to='services.servicepartrequestdecision', verbose_name='Decisión anterior'),
        ),
        migrations.AddField(
            model_name='servicepartrequestdecision',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_decisions', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestdecision',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestinformation',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_information_answered', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AddField(
            model_name='servicepartrequestinformation',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestinformation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_information_closed', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddField(
            model_name='servicepartrequestinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestinformation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestinformation',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_information_requested', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='servicepartrequestinformation',
            name='requested_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_information_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable de responder'),
        ),
        migrations.AddField(
            model_name='servicepartrequestinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestitem',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestitem',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_request_items', to='services.servicechecklistitem', verbose_name='Ítem del checklist'),
        ),
        migrations.AddField(
            model_name='servicepartrequestitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestitem',
            name='source_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_part_request_items', to='equipment.equipmentcomponent', verbose_name='Componente del catálogo'),
        ),
        migrations.AddField(
            model_name='servicepartrequestitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestdecision',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_decisions', to='services.servicepartrequestitem', verbose_name='Detalle del pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestcomment',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='services.servicepartrequestitem', verbose_name='Detalle del pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestattachment',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.servicepartrequestitem', verbose_name='Detalle del pedido'),
        ),
        migrations.AddField(
            model_name='serviceinstallationitem',
            name='part_request_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installation_items', to='services.servicepartrequestitem', verbose_name='Detalle del pedido'),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='part_request_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_item_history', to='services.servicepartrequestitem', verbose_name='Detalle del pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestnotification',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequestnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_part_request_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AddField(
            model_name='servicepartrequestnotification',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestnotification',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.servicepartrequestitem', verbose_name='Detalle del pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequestnotification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequeststatushistory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequeststatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_request_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='servicepartrequeststatushistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartrequeststatushistory',
            name='new_responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_service_part_request_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable nuevo'),
        ),
        migrations.AddField(
            model_name='servicepartrequeststatushistory',
            name='previous_responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_service_part_request_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable anterior'),
        ),
        migrations.AddField(
            model_name='servicepartrequeststatushistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartrequeststatushistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartstockreview',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartstockreview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartstockreview',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reviews', to='services.servicepartrequest', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='servicepartstockreview',
            name='request_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_review', to='services.servicepartrequestitem', verbose_name='Detalle del pedido'),
        ),
        migrations.AddField(
            model_name='servicepartstockreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_stock_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='servicepartstockreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartstockreviewhistory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartstockreviewhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartstockreviewhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_stock_review_events', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='servicepartstockreviewhistory',
            name='stock_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='services.servicepartstockreview', verbose_name='Revisión de stock'),
        ),
        migrations.AddField(
            model_name='servicepartstockreviewhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_transfers_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_transfers_in_custody', to=settings.AUTH_USER_MODEL, verbose_name='Responsable actual'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='destination_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_part_transfers_in', to='equipment.equipment', verbose_name='Equipo de destino'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='handed_over_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_transfers_handed_over', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_transfers_installed', to=settings.AUTH_USER_MODEL, verbose_name='Instalado por'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='part_request_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='services.servicepartrequestitem', verbose_name='Detalle del pedido'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_transfers_received', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='reception_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_part_transfers_to_receive', to=settings.AUTH_USER_MODEL, verbose_name='Técnico de recepción y reposición'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='removal_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_part_transfers_to_remove', to=settings.AUTH_USER_MODEL, verbose_name='Técnico de retiro'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='source_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_part_transfers_out', to='equipment.equipment', verbose_name='Equipo de origen'),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstallationitem',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installation_item', to='services.serviceparttransfer', verbose_name='Transferencia asociada'),
        ),
        migrations.AddField(
            model_name='serviceparttransferhistory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceparttransferhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceparttransferhistory',
            name='new_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_service_part_transfer_custody', to=settings.AUTH_USER_MODEL, verbose_name='Responsable nuevo'),
        ),
        migrations.AddField(
            model_name='serviceparttransferhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_transfer_events', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='serviceparttransferhistory',
            name='previous_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_service_part_transfer_custody', to=settings.AUTH_USER_MODEL, verbose_name='Responsable anterior'),
        ),
        migrations.AddField(
            model_name='serviceparttransferhistory',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='services.serviceparttransfer', verbose_name='Transferencia'),
        ),
        migrations.AddField(
            model_name='serviceparttransferhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereusablepart',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereusablepart',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reusable_service_parts', to='equipment.equipmentcomponent', verbose_name='Parte o unidad'),
        ),
        migrations.AddField(
            model_name='servicereusablepart',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereusablepart',
            name='current_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reusable_parts_installed', to='equipment.equipment', verbose_name='Equipo actual'),
        ),
        migrations.AddField(
            model_name='servicereusablepart',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reusable_parts_in_custody', to=settings.AUTH_USER_MODEL, verbose_name='Responsable actual'),
        ),
        migrations.AddField(
            model_name='servicereusablepart',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reusable_parts_evaluated', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por'),
        ),
        migrations.AddField(
            model_name='servicereusablepart',
            name='source_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reusable_parts_removed', to='equipment.equipment', verbose_name='Equipo de origen'),
        ),
        migrations.AddField(
            model_name='servicereusablepart',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceparttransfer',
            name='reusable_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='services.servicereusablepart', verbose_name='Parte reutilizable'),
        ),
        migrations.AddField(
            model_name='servicepartstockreview',
            name='reusable_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reviews', to='services.servicereusablepart', verbose_name='Parte reutilizable seleccionada'),
        ),
        migrations.AddField(
            model_name='equipmentinstalleditem',
            name='reusable_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installation_history', to='services.servicereusablepart', verbose_name='Parte reutilizable'),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='new_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_reusable_part_history', to='equipment.equipment', verbose_name='Equipo nuevo'),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='new_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_reusable_part_custody', to=settings.AUTH_USER_MODEL, verbose_name='Responsable nuevo'),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reusable_part_events', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='previous_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_reusable_part_history', to='equipment.equipment', verbose_name='Equipo anterior'),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='previous_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_reusable_part_custody', to=settings.AUTH_USER_MODEL, verbose_name='Responsable anterior'),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='reusable_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='services.servicereusablepart', verbose_name='Parte reutilizable'),
        ),
        migrations.AddField(
            model_name='servicereusableparthistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicestatushistory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicestatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicestatushistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicestatushistory',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.serviceorder'),
        ),
        migrations.AddField(
            model_name='servicestatushistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingpoint',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingpoint',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='services.serviceorder'),
        ),
        migrations.AddField(
            model_name='servicetrackingpoint',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tracking_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingpoint',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingsession',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingsession',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='services.serviceorder'),
        ),
        migrations.AddField(
            model_name='servicetrackingsession',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tracking_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingsession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetrackingpoint',
            name='tracking_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='services.servicetrackingsession'),
        ),
        migrations.AddIndex(
            model_name='servicechecklistitem',
            index=models.Index(fields=['checklist', 'status'], name='svc_check_item_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicechecklistitem',
            index=models.Index(fields=['category', 'status'], name='svc_check_cat_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicechecklistitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'component_code', 'position'), name='unique_svc_check_component'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['equipment', 'status'], name='svc_order_equip_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['assigned_technician', 'status'], name='svc_order_tech_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['scheduled_at', 'status'], name='svc_order_sched_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['customer_name', 'status'], name='svc_order_cust_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['service_origin', 'status'], name='svc_order_origin_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemeterreading',
            index=models.Index(fields=['applied_to_equipment_history', 'created_at'], name='svc_meter_applied_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceevidence',
            index=models.Index(fields=['service_order', 'stage'], name='svc_evid_order_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceevidence',
            index=models.Index(fields=['captured_by', 'captured_at'], name='svc_evid_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceevidence',
            constraint=models.UniqueConstraint(fields=('service_order', 'stage', 'sequence'), name='unique_svc_evidence_seq'),
        ),
        migrations.AddIndex(
            model_name='servicechecklist',
            index=models.Index(fields=['status', 'created_at'], name='svc_check_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignmenthistory',
            index=models.Index(fields=['service_order', 'created_at'], name='svc_asg_order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignmenthistory',
            index=models.Index(fields=['new_technician', 'created_at'], name='svc_asg_tech_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequest',
            index=models.Index(fields=['status', 'requested_at'], name='svc_parts_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequest',
            index=models.Index(fields=['current_responsible_area', 'status'], name='svc_parts_area_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequest',
            index=models.Index(fields=['service_order', 'status'], name='svc_parts_order_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestinformation',
            index=models.Index(fields=['request', 'status'], name='svc_pr_info_req_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestinformation',
            index=models.Index(fields=['requested_to_area', 'status'], name='svc_pr_info_area_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestinformation',
            index=models.Index(fields=['requested_to_user', 'status'], name='svc_pr_info_user_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestinformation',
            index=models.Index(fields=['due_at', 'status'], name='svc_pr_info_due_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestitem',
            index=models.Index(fields=['request', 'urgency'], name='svc_part_req_urg_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestitem',
            index=models.Index(fields=['component_code'], name='svc_part_code_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestitem',
            index=models.Index(fields=['item_type', 'management_decision'], name='svc_part_type_dec_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestitem',
            index=models.Index(fields=['supply_method', 'management_decision'], name='svc_part_supply_dec_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestdecision',
            index=models.Index(fields=['request', 'decision'], name='svc_pr_dec_req_dec_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestdecision',
            index=models.Index(fields=['request_item', 'decision'], name='svc_pr_dec_item_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestdecision',
            index=models.Index(fields=['decided_by', 'decided_at'], name='svc_pr_dec_user_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestdecision',
            index=models.Index(fields=['is_final', 'decision'], name='svc_pr_dec_final_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestcomment',
            index=models.Index(fields=['request', 'created_at'], name='svc_pr_com_req_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestcomment',
            index=models.Index(fields=['request_item', 'created_at'], name='svc_pr_com_item_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestcomment',
            index=models.Index(fields=['comment_type', 'created_at'], name='svc_pr_com_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestcomment',
            index=models.Index(fields=['author', 'created_at'], name='svc_pr_com_author_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestcomment',
            index=models.Index(fields=['is_internal', 'created_at'], name='svc_pr_com_internal_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestattachment',
            index=models.Index(fields=['request', 'attachment_type'], name='svc_pr_att_req_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestattachment',
            index=models.Index(fields=['request_item', 'attachment_type'], name='svc_pr_att_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestattachment',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='svc_pr_att_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestattachment',
            index=models.Index(fields=['is_internal', 'created_at'], name='svc_pr_att_internal_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestnotification',
            index=models.Index(fields=['recipient', 'delivery_status', 'created_at'], name='svc_pr_not_rec_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestnotification',
            index=models.Index(fields=['request', 'notification_type'], name='svc_pr_not_req_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestnotification',
            index=models.Index(fields=['channel', 'delivery_status', 'scheduled_at'], name='svc_pr_not_chan_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequestnotification',
            index=models.Index(fields=['request_item', 'notification_type'], name='svc_pr_not_item_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequeststatushistory',
            index=models.Index(fields=['request', 'created_at'], name='svc_pr_hist_req_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequeststatushistory',
            index=models.Index(fields=['new_status', 'created_at'], name='svc_pr_hist_st_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequeststatushistory',
            index=models.Index(fields=['responsible_area', 'created_at'], name='svc_pr_hist_area_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartrequeststatushistory',
            index=models.Index(fields=['changed_by', 'created_at'], name='svc_pr_hist_user_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartstockreviewhistory',
            index=models.Index(fields=['stock_review', 'created_at'], name='svc_stock_hist_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartstockreviewhistory',
            index=models.Index(fields=['event', 'created_at'], name='svc_stock_hist_event_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartstockreviewhistory',
            index=models.Index(fields=['new_status', 'created_at'], name='svc_stock_hist_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartstockreviewhistory',
            index=models.Index(fields=['performed_by', 'created_at'], name='svc_stock_hist_user_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstallationitem',
            index=models.Index(fields=['service_order', 'result'], name='svc_inst_order_res_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstallationitem',
            index=models.Index(fields=['part_request_item', 'result'], name='svc_inst_part_res_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstallationitem',
            index=models.Index(fields=['installed_by', 'installed_at'], name='svc_inst_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstallationitem',
            index=models.Index(fields=['history_generated', 'result'], name='svc_inst_hist_res_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceinstallationitem',
            constraint=models.UniqueConstraint(fields=('service_order', 'part_request_item'), name='unique_svc_install_item'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransferhistory',
            index=models.Index(fields=['transfer', 'created_at'], name='svc_tr_hist_tr_date_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransferhistory',
            index=models.Index(fields=['event', 'created_at'], name='svc_tr_hist_ev_date_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransferhistory',
            index=models.Index(fields=['performed_by', 'created_at'], name='svc_tr_hist_user_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransferhistory',
            index=models.Index(fields=['new_status', 'created_at'], name='svc_tr_hist_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusablepart',
            index=models.Index(fields=['component', 'status'], name='svc_reuse_comp_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusablepart',
            index=models.Index(fields=['source_equipment', 'status'], name='svc_reuse_src_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusablepart',
            index=models.Index(fields=['current_equipment', 'status'], name='svc_reuse_cur_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusablepart',
            index=models.Index(fields=['condition', 'status'], name='svc_reuse_cond_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusablepart',
            index=models.Index(fields=['current_holder', 'status'], name='svc_reuse_hold_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransfer',
            index=models.Index(fields=['status', 'created_at'], name='svc_transfer_st_date_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransfer',
            index=models.Index(fields=['source_equipment', 'status'], name='svc_transfer_src_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransfer',
            index=models.Index(fields=['destination_equipment', 'status'], name='svc_transfer_dst_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransfer',
            index=models.Index(fields=['removal_technician', 'status'], name='svc_transfer_rem_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransfer',
            index=models.Index(fields=['reception_technician', 'status'], name='svc_transfer_rec_st_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceparttransfer',
            index=models.Index(fields=['current_holder', 'status'], name='svc_transfer_hold_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartstockreview',
            index=models.Index(fields=['request', 'status'], name='svc_stock_req_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartstockreview',
            index=models.Index(fields=['status', 'expected_available_at'], name='svc_stock_st_eta_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartstockreview',
            index=models.Index(fields=['reviewed_by', 'reviewed_at'], name='svc_stock_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepartstockreview',
            index=models.Index(fields=['reusable_part', 'status'], name='svc_stock_reuse_st_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinstalleditem',
            index=models.Index(fields=['equipment', 'component', 'color', 'installed_at'], name='svc_inst_hist_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinstalleditem',
            index=models.Index(fields=['equipment', 'item_code', 'installed_at'], name='svc_inst_hist_code_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinstalleditem',
            index=models.Index(fields=['item_type', 'installed_at'], name='svc_inst_hist_type_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinstalleditem',
            index=models.Index(fields=['meter_type', 'reference_meter'], name='svc_inst_hist_meter_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinstalleditem',
            index=models.Index(fields=['source_equipment', 'installed_at'], name='svc_inst_hist_source_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusableparthistory',
            index=models.Index(fields=['reusable_part', 'created_at'], name='svc_reuse_hist_part_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusableparthistory',
            index=models.Index(fields=['event', 'created_at'], name='svc_reuse_hist_event_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusableparthistory',
            index=models.Index(fields=['new_status', 'created_at'], name='svc_reuse_hist_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereusableparthistory',
            index=models.Index(fields=['performed_by', 'created_at'], name='svc_reuse_hist_user_idx'),
        ),
        migrations.AddIndex(
            model_name='servicestatushistory',
            index=models.Index(fields=['service_order', 'created_at'], name='svc_hist_order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicestatushistory',
            index=models.Index(fields=['new_status', 'created_at'], name='svc_hist_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetrackingsession',
            index=models.Index(fields=['service_order', 'status'], name='svc_track_order_st_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetrackingsession',
            index=models.Index(fields=['technician', 'status'], name='svc_track_tech_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicetrackingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('status', 'active')), fields=('service_order',), name='unique_active_svc_tracking'),
        ),
        migrations.AddIndex(
            model_name='servicetrackingpoint',
            index=models.Index(fields=['service_order', 'device_recorded_at'], name='svc_point_order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetrackingpoint',
            index=models.Index(fields=['tracking_session', 'device_recorded_at'], name='svc_point_sess_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetrackingpoint',
            index=models.Index(fields=['is_mock_location', 'device_recorded_at'], name='svc_point_mock_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicetrackingpoint',
            constraint=models.UniqueConstraint(fields=('tracking_session', 'sequence_number'), name='unique_svc_track_sequence'),
        ),
    ]
