# Generated by Django 5.2.16 on 2026-07-27 17:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_componentinventory_componentinventorymovement_and_more'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service_origin',
            field=models.CharField(choices=[('rental', 'Alquiler Andes'), ('external', 'Alquiler o equipo externo')], db_index=True, default='rental', max_length=20, verbose_name='Origen de la atención'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='address',
            field=models.TextField(verbose_name='Dirección histórica'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='address_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Referencia de dirección'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de llegada'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='assigned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='branch_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Sede histórica'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='closure_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones de cierre'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, unique=True, verbose_name='Número de OS'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del contacto'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='contact_job_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo del contacto'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contacto histórico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono del contacto'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='contract_reference',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Referencia del contrato'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código del cliente'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='customer_document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='customer_document_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Cliente histórico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='customer_trade_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre comercial'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Latitud del destino'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Longitud del destino'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='equipment_brand_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Marca histórica'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='equipment_family_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Familia histórica'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='equipment_internal_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código interno histórico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='equipment_model_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modelo histórico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='equipment_serial_number',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Serie histórica'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='failed_visit_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de visita no realizada'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(default=150, verbose_name='Radio de geocerca'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='normal', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='rental_assignment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Referencia de asignación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='reported_problem',
            field=models.TextField(verbose_name='Problema reportado'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='requested_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='requires_return_visit',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Requiere nueva visita'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='result',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('operational', 'Operativa'), ('operational_with_notes', 'Operativa con observaciones'), ('pending_parts', 'Pendiente de repuestos'), ('requires_return', 'Requiere nueva visita'), ('not_repaired', 'No reparada'), ('not_attended', 'No atendida')], db_index=True, default='pending', max_length=40, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='route_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de ruta'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio del servicio'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_type',
            field=models.CharField(choices=[('preventive', 'Preventivo'), ('corrective', 'Correctivo'), ('network', 'Red y configuración'), ('meter_reading', 'Lectura de contadores'), ('inspection', 'Inspección'), ('other', 'Otro')], db_index=True, default='corrective', max_length=40, verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='site_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ubicación dentro de la sede'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_assignment', 'Pendiente de asignación'), ('assigned', 'Asignada'), ('accepted', 'Aceptada por técnico'), ('en_route', 'Técnico en ruta'), ('on_site', 'Técnico en ubicación'), ('in_progress', 'En proceso'), ('pending_parts', 'Pendiente de repuestos'), ('requires_return', 'Requiere nueva visita'), ('technician_completed', 'Finalizada por técnico'), ('pending_conformity', 'Pendiente de conformidad'), ('closed', 'Cerrada'), ('rescheduled', 'Reprogramada'), ('failed_visit', 'Visita no realizada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='technician_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalización del técnico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='technician_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones del técnico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='work_performed',
            field=models.TextField(blank=True, verbose_name='Trabajo realizado'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['service_origin', 'status'], name='svc_order_origin_st_idx'),
        ),
    ]
