# -*- coding: utf-8 -*-
from django.urls import path

from .views import (
    ApplyMeterReadingView,
    ArchiveComponentCompatibilityView,
    ArchiveComponentTypeView,
    ArchiveEquipmentBrandView,
    ArchiveEquipmentComponentView,
    ArchiveEquipmentDocumentView,
    ArchiveEquipmentFamilyView,
    ArchiveEquipmentModelView,
    ArchiveEquipmentMovementView,
    ArchiveEquipmentTypeView,
    ArchiveEquipmentView,
    ArchiveImportBatchView,
    ArchiveMeterReadingView,
    ChangeEquipmentCommercialStatusView,
    ChangeEquipmentTechnicalStatusView,
    ChangeImportBatchStatusView,
    ComponentCompatibilityDetailUpdateView,
    ComponentCompatibilityListCreateView,
    ComponentTypeDetailUpdateView,
    ComponentTypeListCreateView,
    EquipmentBrandDetailUpdateView,
    EquipmentBrandListCreateView,
    EquipmentComponentAssignmentDetailUpdateView,
    EquipmentComponentAssignmentListCreateView,
    EquipmentComponentDetailUpdateView,
    EquipmentComponentListCreateView,
    EquipmentDetailUpdateView,
    EquipmentDocumentDetailUpdateView,
    EquipmentDocumentListCreateView,
    EquipmentFamilyDetailUpdateView,
    EquipmentFamilyListCreateView,
    EquipmentListCreateView,
    EquipmentModelDetailUpdateView,
    EquipmentModelListCreateView,
    EquipmentMovementDetailUpdateView,
    EquipmentMovementListCreateView,
    EquipmentTypeDetailUpdateView,
    EquipmentTypeListCreateView,
    ImportBatchDetailUpdateView,
    ImportBatchListCreateView,
    MeterReadingDetailUpdateView,
    MeterReadingListCreateView,
    RegisterInitialEquipmentMetersView,
    RemoveEquipmentDocumentVerificationView,
    RestoreComponentCompatibilityView,
    RestoreComponentTypeView,
    RestoreEquipmentBrandView,
    RestoreEquipmentComponentView,
    RestoreEquipmentDocumentView,
    RestoreEquipmentFamilyView,
    RestoreEquipmentModelView,
    RestoreEquipmentMovementView,
    RestoreEquipmentTypeView,
    RestoreEquipmentView,
    RestoreImportBatchView,
    RestoreMeterReadingView,
    VerifyEquipmentDocumentView,
    VerifyMeterReadingView,
)


app_name = "equipment"


urlpatterns = [
    path(
        "",
        EquipmentListCreateView.as_view(),
        name="equipment-list-create",
    ),
    path(
        "<uuid:id>/",
        EquipmentDetailUpdateView.as_view(),
        name="equipment-detail-update",
    ),
    path(
        "<uuid:equipment_id>/technical-status/",
        ChangeEquipmentTechnicalStatusView.as_view(),
        name="equipment-change-technical-status",
    ),
    path(
        "<uuid:equipment_id>/commercial-status/",
        ChangeEquipmentCommercialStatusView.as_view(),
        name="equipment-change-commercial-status",
    ),
    path(
        "<uuid:equipment_id>/initial-meters/",
        RegisterInitialEquipmentMetersView.as_view(),
        name="equipment-register-initial-meters",
    ),
    path(
        "<uuid:equipment_id>/archive/",
        ArchiveEquipmentView.as_view(),
        name="equipment-archive",
    ),
    path(
        "<uuid:equipment_id>/restore/",
        RestoreEquipmentView.as_view(),
        name="equipment-restore",
    ),

    path(
        "types/",
        EquipmentTypeListCreateView.as_view(),
        name="equipment-type-list-create",
    ),
    path(
        "types/<uuid:id>/",
        EquipmentTypeDetailUpdateView.as_view(),
        name="equipment-type-detail-update",
    ),
    path(
        "types/<uuid:equipment_type_id>/archive/",
        ArchiveEquipmentTypeView.as_view(),
        name="equipment-type-archive",
    ),
    path(
        "types/<uuid:equipment_type_id>/restore/",
        RestoreEquipmentTypeView.as_view(),
        name="equipment-type-restore",
    ),

    path(
        "brands/",
        EquipmentBrandListCreateView.as_view(),
        name="equipment-brand-list-create",
    ),
    path(
        "brands/<uuid:id>/",
        EquipmentBrandDetailUpdateView.as_view(),
        name="equipment-brand-detail-update",
    ),
    path(
        "brands/<uuid:brand_id>/archive/",
        ArchiveEquipmentBrandView.as_view(),
        name="equipment-brand-archive",
    ),
    path(
        "brands/<uuid:brand_id>/restore/",
        RestoreEquipmentBrandView.as_view(),
        name="equipment-brand-restore",
    ),

    path(
        "families/",
        EquipmentFamilyListCreateView.as_view(),
        name="equipment-family-list-create",
    ),
    path(
        "families/<uuid:id>/",
        EquipmentFamilyDetailUpdateView.as_view(),
        name="equipment-family-detail-update",
    ),
    path(
        "families/<uuid:equipment_family_id>/archive/",
        ArchiveEquipmentFamilyView.as_view(),
        name="equipment-family-archive",
    ),
    path(
        "families/<uuid:equipment_family_id>/restore/",
        RestoreEquipmentFamilyView.as_view(),
        name="equipment-family-restore",
    ),

    path(
        "models/",
        EquipmentModelListCreateView.as_view(),
        name="equipment-model-list-create",
    ),
    path(
        "models/<uuid:id>/",
        EquipmentModelDetailUpdateView.as_view(),
        name="equipment-model-detail-update",
    ),
    path(
        "models/<uuid:equipment_model_id>/archive/",
        ArchiveEquipmentModelView.as_view(),
        name="equipment-model-archive",
    ),
    path(
        "models/<uuid:equipment_model_id>/restore/",
        RestoreEquipmentModelView.as_view(),
        name="equipment-model-restore",
    ),

    path(
        "component-types/",
        ComponentTypeListCreateView.as_view(),
        name="component-type-list-create",
    ),
    path(
        "component-types/<uuid:id>/",
        ComponentTypeDetailUpdateView.as_view(),
        name="component-type-detail-update",
    ),
    path(
        "component-types/<uuid:component_type_id>/archive/",
        ArchiveComponentTypeView.as_view(),
        name="component-type-archive",
    ),
    path(
        "component-types/<uuid:component_type_id>/restore/",
        RestoreComponentTypeView.as_view(),
        name="component-type-restore",
    ),

    path(
        "components/",
        EquipmentComponentListCreateView.as_view(),
        name="equipment-component-list-create",
    ),
    path(
        "components/<uuid:id>/",
        EquipmentComponentDetailUpdateView.as_view(),
        name="equipment-component-detail-update",
    ),
    path(
        "components/<uuid:component_id>/archive/",
        ArchiveEquipmentComponentView.as_view(),
        name="equipment-component-archive",
    ),
    path(
        "components/<uuid:component_id>/restore/",
        RestoreEquipmentComponentView.as_view(),
        name="equipment-component-restore",
    ),

    path(
        "component-compatibilities/",
        ComponentCompatibilityListCreateView.as_view(),
        name="component-compatibility-list-create",
    ),
    path(
        "component-compatibilities/<uuid:id>/",
        ComponentCompatibilityDetailUpdateView.as_view(),
        name="component-compatibility-detail-update",
    ),
    path(
        "component-compatibilities/<uuid:compatibility_id>/archive/",
        ArchiveComponentCompatibilityView.as_view(),
        name="component-compatibility-archive",
    ),
    path(
        "component-compatibilities/<uuid:compatibility_id>/restore/",
        RestoreComponentCompatibilityView.as_view(),
        name="component-compatibility-restore",
    ),

    path(
        "component-assignments/",
        EquipmentComponentAssignmentListCreateView.as_view(),
        name="equipment-component-assignment-list-create",
    ),
    path(
        "component-assignments/<uuid:id>/",
        EquipmentComponentAssignmentDetailUpdateView.as_view(),
        name="equipment-component-assignment-detail-update",
    ),

    path(
        "import-batches/",
        ImportBatchListCreateView.as_view(),
        name="import-batch-list-create",
    ),
    path(
        "import-batches/<uuid:id>/",
        ImportBatchDetailUpdateView.as_view(),
        name="import-batch-detail-update",
    ),
    path(
        "import-batches/<uuid:import_batch_id>/status/",
        ChangeImportBatchStatusView.as_view(),
        name="import-batch-change-status",
    ),
    path(
        "import-batches/<uuid:import_batch_id>/archive/",
        ArchiveImportBatchView.as_view(),
        name="import-batch-archive",
    ),
    path(
        "import-batches/<uuid:import_batch_id>/restore/",
        RestoreImportBatchView.as_view(),
        name="import-batch-restore",
    ),

    path(
        "movements/",
        EquipmentMovementListCreateView.as_view(),
        name="equipment-movement-list-create",
    ),
    path(
        "movements/<uuid:id>/",
        EquipmentMovementDetailUpdateView.as_view(),
        name="equipment-movement-detail-update",
    ),
    path(
        "movements/<uuid:movement_id>/archive/",
        ArchiveEquipmentMovementView.as_view(),
        name="equipment-movement-archive",
    ),
    path(
        "movements/<uuid:movement_id>/restore/",
        RestoreEquipmentMovementView.as_view(),
        name="equipment-movement-restore",
    ),

    path(
        "meter-readings/",
        MeterReadingListCreateView.as_view(),
        name="meter-reading-list-create",
    ),
    path(
        "meter-readings/<uuid:id>/",
        MeterReadingDetailUpdateView.as_view(),
        name="meter-reading-detail-update",
    ),
    path(
        "meter-readings/<uuid:reading_id>/verify/",
        VerifyMeterReadingView.as_view(),
        name="meter-reading-verify",
    ),
    path(
        "meter-readings/<uuid:reading_id>/apply/",
        ApplyMeterReadingView.as_view(),
        name="meter-reading-apply",
    ),
    path(
        "meter-readings/<uuid:reading_id>/archive/",
        ArchiveMeterReadingView.as_view(),
        name="meter-reading-archive",
    ),
    path(
        "meter-readings/<uuid:reading_id>/restore/",
        RestoreMeterReadingView.as_view(),
        name="meter-reading-restore",
    ),

    path(
        "documents/",
        EquipmentDocumentListCreateView.as_view(),
        name="equipment-document-list-create",
    ),
    path(
        "documents/<uuid:id>/",
        EquipmentDocumentDetailUpdateView.as_view(),
        name="equipment-document-detail-update",
    ),
    path(
        "documents/<uuid:document_id>/verify/",
        VerifyEquipmentDocumentView.as_view(),
        name="equipment-document-verify",
    ),
    path(
        "documents/<uuid:document_id>/remove-verification/",
        RemoveEquipmentDocumentVerificationView.as_view(),
        name="equipment-document-remove-verification",
    ),
    path(
        "documents/<uuid:document_id>/archive/",
        ArchiveEquipmentDocumentView.as_view(),
        name="equipment-document-archive",
    ),
    path(
        "documents/<uuid:document_id>/restore/",
        RestoreEquipmentDocumentView.as_view(),
        name="equipment-document-restore",
    ),
]