# Generated by Django 5.2.16 on 2026-08-01 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcompatibility',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='componentcompatibility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='componentcompatibility',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Asesor comercial'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Cliente para el cual el equipo fue separado, vendido, entregado o asignado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_equipment', to='partners.partner', verbose_name='Cliente relacionado'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer_branch',
            field=models.ForeignKey(blank=True, help_text='Sucursal, obra, proyecto o local al cual se encuentra relacionado el equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_equipment', to='partners.partnerbranch', verbose_name='Sucursal del cliente'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner_partner',
            field=models.ForeignKey(blank=True, help_text='Se utiliza cuando el equipo pertenece a un cliente, proveedor o tercero.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_external_equipment', to='partners.partner', verbose_name='Propietario externo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Proveedor directo de esta máquina. Puede heredarse conceptualmente del lote, pero se guarda para identificar casos especiales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplied_equipment', to='partners.partner', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unloading_registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloaded_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Registrado en descarga por'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipmentbrand',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipmentbrand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipmentbrand',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipmentcomponent',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipmentcomponent',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='equipment.componenttype', verbose_name='Tipo de componente'),
        ),
        migrations.AddField(
            model_name='equipmentcomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipmentcomponent',
            name='parent_component',
            field=models.ForeignKey(blank=True, help_text='Relaciona una subparte con la unidad o componente principal al que pertenece. Por ejemplo, un rodillo de presión dentro de una unidad fusora.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcomponents', to='equipment.equipmentcomponent', verbose_name='Componente principal'),
        ),
        migrations.AddField(
            model_name='equipmentcomponent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='componentcompatibility',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compatibilities', to='equipment.equipmentcomponent', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='equipmentcomponentassignment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipmentcomponentassignment',
            name='component',
            field=models.ForeignKey(help_text='Unidad, subparte, repuesto, accesorio, tóner o consumible relacionado con el equipo.', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to='equipment.equipmentcomponent', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='equipmentcomponentassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipmentcomponentassignment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_assignments', to='equipment.equipment', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='equipmentcomponentassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipmentdocument',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipmentdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipmentdocument',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='equipment.equipment', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='equipmentdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipmentdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_equipment_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='equipmentdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_equipment_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='equipmentfamily',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipmentfamily',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_families', to='equipment.equipmentbrand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='equipmentfamily',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipmentfamily',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='componentcompatibility',
            name='equipment_family',
            field=models.ForeignKey(help_text='Familia para la cual el componente es compatible.', on_delete=django.db.models.deletion.PROTECT, related_name='component_compatibilities', to='equipment.equipmentfamily', verbose_name='Familia de equipos'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='equipment.equipmentbrand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='equipment_family',
            field=models.ForeignKey(blank=True, help_text='Familia controlada utilizada para definir compatibilidad de unidades, subpartes, accesorios, tóners y repuestos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='equipment.equipmentfamily', verbose_name='Familia de equipos'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_units', to='equipment.equipmentmodel', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='componentcompatibility',
            name='equipment_model',
            field=models.ForeignKey(blank=True, help_text='Solo debe seleccionarse cuando la compatibilidad aplica a un modelo específico dentro de la familia.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_compatibilities', to='equipment.equipmentmodel', verbose_name='Modelo específico'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='equipment.equipment', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='new_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_advisor_equipment_movements', to=settings.AUTH_USER_MODEL, verbose_name='Nuevo asesor'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='new_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_equipment_movements', to='partners.partner', verbose_name='Nuevo cliente'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='new_customer_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_equipment_movements', to='partners.partnerbranch', verbose_name='Nueva sucursal'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='new_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_owned_equipment_movements', to='partners.partner', verbose_name='Nuevo propietario'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='previous_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_advisor_equipment_movements', to=settings.AUTH_USER_MODEL, verbose_name='Asesor anterior'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='previous_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_equipment_movements', to='partners.partner', verbose_name='Cliente anterior'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='previous_customer_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_equipment_movements', to='partners.partnerbranch', verbose_name='Sucursal anterior'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='previous_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_owned_equipment_movements', to='partners.partner', verbose_name='Propietario anterior'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó o confirmó físicamente el movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_equipment_movements', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del movimiento'),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='equipment.equipmenttype', verbose_name='Tipo de equipo'),
        ),
        migrations.AddField(
            model_name='equipmentfamily',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_families', to='equipment.equipmenttype', verbose_name='Tipo de equipo'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='supplier',
            field=models.ForeignKey(help_text='Proveedor, empresa o tercero del que proceden los equipos.', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_import_batches', to='partners.partner', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='Importación, compra o lote mediante el cual ingresó el equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_units', to='equipment.importbatch', verbose_name='Importación o lote'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='equipment.equipment', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_equipment_meter_readings', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_equipment_meter_readings', to=settings.AUTH_USER_MODEL, verbose_name='Verificada por'),
        ),
        migrations.AddIndex(
            model_name='componenttype',
            index=models.Index(fields=['category', 'is_active'], name='equip_comp_type_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='componenttype',
            index=models.Index(fields=['is_active', 'display_order'], name='eq_comp_type_order_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentbrand',
            index=models.Index(fields=['is_active', 'display_order'], name='equip_brand_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponent',
            index=models.Index(fields=['component_type', 'is_active'], name='eq_comp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponent',
            index=models.Index(fields=['parent_component', 'is_active'], name='eq_comp_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponent',
            index=models.Index(fields=['color', 'is_active'], name='eq_comp_color_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponent',
            index=models.Index(fields=['is_consumable', 'is_active'], name='eq_comp_consum_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponent',
            index=models.Index(fields=['manufacturer_code', 'is_active'], name='eq_comp_mfr_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentcomponent',
            constraint=models.UniqueConstraint(fields=('component_type', 'name', 'color'), name='unique_component_type_name_color'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponentassignment',
            index=models.Index(fields=['equipment', 'is_active'], name='equip_comp_assign_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponentassignment',
            index=models.Index(fields=['component', 'status'], name='eq_comp_asg_component_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponentassignment',
            index=models.Index(fields=['reference_type', 'reference_id'], name='equip_comp_assign_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponentassignment',
            index=models.Index(fields=['status', 'installed_at'], name='equip_comp_assign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcomponentassignment',
            index=models.Index(fields=['serial_number'], name='equip_comp_asg_serial_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentcomponentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'installed')), fields=('equipment', 'component', 'position'), name='unique_active_component_position'),
        ),
        migrations.AddConstraint(
            model_name='equipmentcomponentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('component', 'serial_number'), name='unique_assigned_component_serial'),
        ),
        migrations.AddIndex(
            model_name='equipmentdocument',
            index=models.Index(fields=['equipment', 'document_type'], name='equip_doc_equipment_type_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdocument',
            index=models.Index(fields=['equipment', 'document_date'], name='equip_doc_equipment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdocument',
            index=models.Index(fields=['reference_type', 'reference_id'], name='equip_doc_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdocument',
            index=models.Index(fields=['document_type', 'is_active'], name='equip_doc_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdocument',
            index=models.Index(fields=['is_verified', 'is_active'], name='equip_doc_verified_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_primary', True)), fields=('equipment', 'document_type'), name='unique_primary_equipment_document_type'),
        ),
        migrations.AddIndex(
            model_name='componentcompatibility',
            index=models.Index(fields=['equipment_family', 'is_active'], name='comp_compat_family_active_idx'),
        ),
        migrations.AddIndex(
            model_name='componentcompatibility',
            index=models.Index(fields=['equipment_model', 'is_active'], name='comp_compat_model_active_idx'),
        ),
        migrations.AddIndex(
            model_name='componentcompatibility',
            index=models.Index(fields=['component', 'is_active'], name='comp_compat_component_idx'),
        ),
        migrations.AddIndex(
            model_name='componentcompatibility',
            index=models.Index(fields=['position', 'is_active'], name='comp_compat_position_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentcompatibility',
            constraint=models.UniqueConstraint(fields=('component', 'equipment_family', 'equipment_model', 'position'), name='unique_component_family_model_position'),
        ),
        migrations.AddIndex(
            model_name='equipmentmovement',
            index=models.Index(fields=['equipment', 'occurred_at'], name='equip_move_equipment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmovement',
            index=models.Index(fields=['equipment', 'movement_type'], name='equip_move_equipment_type_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmovement',
            index=models.Index(fields=['movement_type', 'occurred_at'], name='equip_move_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='equip_move_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmovement',
            index=models.Index(fields=['new_customer', 'occurred_at'], name='equip_move_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmenttype',
            index=models.Index(fields=['is_active', 'display_order'], name='equip_type_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['brand', 'is_active'], name='equip_model_brand_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['equipment_type', 'is_active'], name='equip_model_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['family', 'is_active'], name='equip_model_family_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['equipment_family', 'is_active'], name='equip_model_eq_family_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_equipment_model_brand_name'),
        ),
        migrations.AddIndex(
            model_name='equipmentfamily',
            index=models.Index(fields=['brand', 'is_active'], name='equip_family_brand_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfamily',
            index=models.Index(fields=['equipment_type', 'is_active'], name='equip_family_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfamily',
            index=models.Index(fields=['is_active', 'display_order'], name='equip_family_active_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentfamily',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_equipment_family_brand_name'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['supplier', 'status'], name='eq_batch_supplier_status'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['purchase_type', 'status'], name='equip_batch_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['arrival_date', 'status'], name='equip_batch_arrival_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['technical_status', 'commercial_status'], name='equip_technical_commercial_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_available', 'is_active'], name='equip_available_active_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_model', 'technical_status'], name='equip_model_technical_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['customer', 'commercial_status'], name='equip_customer_commercial_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['import_batch', 'unloading_date'], name='equip_batch_unloading_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['warehouse_location', 'is_available'], name='equip_location_available_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['equipment', 'reading_date'], name='equip_meter_equipment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['equipment', 'source'], name='eq_meter_equip_source'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['source', 'reading_date'], name='equip_meter_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['reference_type', 'reference_id'], name='equip_meter_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['is_verified', 'reading_date'], name='equip_meter_verified_date_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['is_applied_to_equipment', 'reading_date'], name='equip_meter_applied_date_idx'),
        ),
    ]
