# Generated by Django 5.2.16 on 2026-08-01 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        ('partners', '0002_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalassignment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalassignment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_assignments', to='partners.partnerbranch', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='rentalassignment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_assignments', to='partners.partnercontact', verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='rentalassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalassignment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_assignments', to='partners.partner', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='rentalassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_contracts', to='partners.partner', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='main_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_rental_contracts', to='partners.partnerbranch', verbose_name='Sede principal'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='main_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_rental_contracts', to='partners.partnercontact', verbose_name='Contacto principal'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentalassignment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rentals.rentalcontract', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='rentals.rentalassignment', verbose_name='Asignación'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='rentals.rentalcontract', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentalequipment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalequipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalequipment',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rental_profile', to='equipment.equipment', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='rentalequipment',
            name='owner_customer',
            field=models.ForeignKey(blank=True, help_text='Se utiliza cuando el equipo pertenece a un cliente externo y solo está registrado para servicios técnicos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_service_equipment', to='partners.partner', verbose_name='Cliente propietario'),
        ),
        migrations.AddField(
            model_name='rentalequipment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_equipment_supplied', to='partners.partner', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='rentalequipment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='rental_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_documents', to='rentals.rentalequipment', verbose_name='Equipo de alquiler'),
        ),
        migrations.AddField(
            model_name='rentalassignment',
            name='rental_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rentals.rentalequipment', verbose_name='Equipo de alquiler'),
        ),
        migrations.AddField(
            model_name='rentalequipmentmovement',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalequipmentmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalequipmentmovement',
            name='rental_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='rentals.rentalequipment', verbose_name='Equipo de alquiler'),
        ),
        migrations.AddField(
            model_name='rentalequipmentmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentalinstallation',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalinstallation',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_installations_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AddField(
            model_name='rentalinstallation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalinstallation',
            name='rental_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='rentals.rentalassignment', verbose_name='Asignación de alquiler'),
        ),
        migrations.AddField(
            model_name='rentalinstallation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='rentals.rentalinstallation', verbose_name='Instalación'),
        ),
        migrations.AddField(
            model_name='rentalpreparation',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalpreparation',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_preparations_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AddField(
            model_name='rentalpreparation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalpreparation',
            name='rental_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparations', to='rentals.rentalequipment', verbose_name='Equipo de alquiler'),
        ),
        migrations.AddField(
            model_name='rentalpreparation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='rentals.rentalpreparation', verbose_name='Preparación'),
        ),
        migrations.AddField(
            model_name='rentalremoval',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalremoval',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_removals_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AddField(
            model_name='rentalremoval',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalremoval',
            name='rental_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='removals', to='rentals.rentalassignment', verbose_name='Asignación de alquiler'),
        ),
        migrations.AddField(
            model_name='rentalremoval',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='removal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='rentals.rentalremoval', verbose_name='Retiro'),
        ),
        migrations.AddField(
            model_name='rentalreplacement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_replacements_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='rentalreplacement',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalreplacement',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_replacements_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AddField(
            model_name='rentalreplacement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalreplacement',
            name='incoming_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_entries', to='rentals.rentalequipment', verbose_name='Equipo de reemplazo'),
        ),
        migrations.AddField(
            model_name='rentalreplacement',
            name='outgoing_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_departures', to='rentals.rentalequipment', verbose_name='Equipo retirado'),
        ),
        migrations.AddField(
            model_name='rentalreplacement',
            name='rental_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='rentals.rentalassignment', verbose_name='Asignación afectada'),
        ),
        migrations.AddField(
            model_name='rentalreplacement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='rentals.rentalreplacement', verbose_name='Reemplazo'),
        ),
        migrations.AddField(
            model_name='rentalwarehouse',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='rentalwarehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='rentalwarehouse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='rentalremoval',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_removals_received', to='rentals.rentalwarehouse', verbose_name='Almacén de destino'),
        ),
        migrations.AddField(
            model_name='rentalequipmentmovement',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_equipment_movements', to='rentals.rentalwarehouse', verbose_name='Almacén de destino'),
        ),
        migrations.AddField(
            model_name='rentalequipmentmovement',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_equipment_movements', to='rentals.rentalwarehouse', verbose_name='Almacén de origen'),
        ),
        migrations.AddField(
            model_name='rentalequipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='rentals.rentalwarehouse', verbose_name='Almacén actual'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['customer', 'status'], name='rent_ctr_customer_st_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['status', 'start_date'], name='rent_contract_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['status', 'end_date'], name='rent_contract_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['contract_type', 'status'], name='rent_contract_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalassignment',
            index=models.Index(fields=['contract', 'status'], name='rent_asg_contract_st_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalassignment',
            index=models.Index(fields=['rental_equipment', 'status'], name='rent_asg_equipment_st_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalassignment',
            index=models.Index(fields=['customer', 'branch', 'status'], name='rent_asg_customer_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('status__in', ['reserved', 'installation_pending', 'installed', 'active', 'removal_pending'])), fields=('rental_equipment',), name='unique_active_rental_assignment'),
        ),
        migrations.AddIndex(
            model_name='rentalinstallation',
            index=models.Index(fields=['rental_assignment', 'status'], name='rent_install_assign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalinstallation',
            index=models.Index(fields=['assigned_technician', 'status'], name='rent_install_tech_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalinstallation',
            index=models.Index(fields=['status', 'scheduled_at'], name='rent_install_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalinstallation',
            index=models.Index(fields=['result', 'completed_at'], name='rent_install_result_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalpreparation',
            index=models.Index(fields=['rental_equipment', 'status'], name='rent_prep_equipment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalpreparation',
            index=models.Index(fields=['assigned_technician', 'status'], name='rent_prep_tech_st_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalpreparation',
            index=models.Index(fields=['status', 'scheduled_date'], name='rent_prep_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalpreparation',
            index=models.Index(fields=['result', 'completed_at'], name='rent_prep_result_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalreplacement',
            index=models.Index(fields=['rental_assignment', 'status'], name='rent_repl_assign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalreplacement',
            index=models.Index(fields=['outgoing_equipment', 'status'], name='rent_repl_out_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalreplacement',
            index=models.Index(fields=['incoming_equipment', 'status'], name='rent_repl_in_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalreplacement',
            index=models.Index(fields=['assigned_technician', 'status'], name='rent_repl_tech_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalreplacement',
            index=models.Index(fields=['status', 'scheduled_at'], name='rent_repl_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaldocument',
            index=models.Index(fields=['rental_equipment', 'document_type'], name='rent_doc_equipment_type_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaldocument',
            index=models.Index(fields=['contract', 'document_type'], name='rent_doc_contract_type_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaldocument',
            index=models.Index(fields=['document_type', 'issued_date'], name='rent_doc_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalwarehouse',
            index=models.Index(fields=['is_active', 'display_order'], name='rent_warehouse_active_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalremoval',
            index=models.Index(fields=['rental_assignment', 'status'], name='rent_remove_assign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalremoval',
            index=models.Index(fields=['assigned_technician', 'status'], name='rent_remove_tech_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalremoval',
            index=models.Index(fields=['status', 'scheduled_at'], name='rent_remove_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalremoval',
            index=models.Index(fields=['result', 'completed_at'], name='rent_remove_result_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalequipmentmovement',
            index=models.Index(fields=['rental_equipment', 'occurred_at'], name='rent_eq_mov_equipment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalequipmentmovement',
            index=models.Index(fields=['movement_type', 'occurred_at'], name='rent_eq_mov_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalequipmentmovement',
            index=models.Index(fields=['new_status', 'occurred_at'], name='rent_eq_mov_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalequipmentmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='rent_eq_mov_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalequipment',
            index=models.Index(fields=['purpose', 'operational_status'], name='rent_equip_purpose_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalequipment',
            index=models.Index(fields=['warehouse', 'operational_status'], name='rent_eq_warehouse_st_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalequipment',
            index=models.Index(fields=['is_available_for_rental', 'operational_status'], name='rent_equip_available_idx'),
        ),
    ]
