# Generated by Django 5.2.16 on 2026-08-01 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlookuplog',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='documentlookuplog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='documentlookuplog',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_document_lookups', to=settings.AUTH_USER_MODEL, verbose_name='Consultado por'),
        ),
        migrations.AddField(
            model_name='documentlookuplog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='partner',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partners', to=settings.AUTH_USER_MODEL, verbose_name='Asesora o responsable comercial'),
        ),
        migrations.AddField(
            model_name='partner',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='partner',
            name='purchasing_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_supplier_partners', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de compras'),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='documentlookuplog',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Se completa cuando la consulta se utiliza para crear o actualizar un tercero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_lookups', to='partners.partner', verbose_name='Tercero relacionado'),
        ),
        migrations.AddField(
            model_name='partnerbranch',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Si se deja vacío, se utilizará la asesora principal del cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partner_branches', to=settings.AUTH_USER_MODEL, verbose_name='Asesora responsable de la sede'),
        ),
        migrations.AddField(
            model_name='partnerbranch',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='partnerbranch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='partnerbranch',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='partners.partner', verbose_name='Cliente, proveedor o distribuidor'),
        ),
        migrations.AddField(
            model_name='partnerbranch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Puede dejarse vacío cuando el contacto corresponde a toda la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='partners.partnerbranch', verbose_name='Sucursal o sede'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='partners.partner', verbose_name='Cliente, proveedor o distribuidor'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['country_code', 'document_number'], name='partners_country_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['is_active', 'archived_at'], name='partners_active_archive_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['advisor', 'is_active'], name='partners_advisor_active_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['sunat_status', 'sunat_condition'], name='partners_sunat_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('country_code', 'document_type', 'document_number'), name='partners_unique_document'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('is_rental_customer', True), ('is_sales_customer', True), ('is_service_customer', True), ('is_supplier', True), ('is_distributor', True), _connector='OR'), name='partners_requires_role'),
        ),
        migrations.AddIndex(
            model_name='documentlookuplog',
            index=models.Index(fields=['document_type', 'document_number', 'created_at'], name='partners_lookup_document_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlookuplog',
            index=models.Index(fields=['requested_by', 'created_at'], name='partners_lookup_user_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlookuplog',
            index=models.Index(fields=['status', 'created_at'], name='partners_lookup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlookuplog',
            index=models.Index(fields=['partner', 'created_at'], name='partners_lookup_partner_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlookuplog',
            index=models.Index(fields=['provider', 'http_status_code'], name='partners_lookup_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerbranch',
            index=models.Index(fields=['partner', 'is_active'], name='partners_branch_active_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerbranch',
            index=models.Index(fields=['partner', 'branch_type'], name='partners_branch_type_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerbranch',
            index=models.Index(fields=['district', 'province', 'region'], name='partners_branch_location_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerbranch',
            index=models.Index(fields=['allows_equipment_installation', 'is_active'], name='partners_branch_install_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerbranch',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('partner', 'code'), name='partners_unique_branch_code'),
        ),
        migrations.AddConstraint(
            model_name='partnerbranch',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_main', True)), fields=('partner',), name='partners_unique_main_branch'),
        ),
        migrations.AddConstraint(
            model_name='partnerbranch',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_fiscal', True)), fields=('partner',), name='partners_unique_fiscal_branch'),
        ),
        migrations.AddIndex(
            model_name='partnercontact',
            index=models.Index(fields=['partner', 'is_active'], name='partners_contact_active_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercontact',
            index=models.Index(fields=['partner', 'area'], name='partners_contact_area_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercontact',
            index=models.Index(fields=['branch', 'is_active'], name='partners_contact_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercontact',
            index=models.Index(fields=['receives_billing', 'is_active'], name='partners_contact_billing_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercontact',
            index=models.Index(fields=['receives_service_notifications', 'is_active'], name='partners_contact_service_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnercontact',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_active', True), ('is_primary', True)), fields=('partner',), name='partners_unique_primary_contact'),
        ),
        migrations.AddConstraint(
            model_name='partnercontact',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('document_type', ''), _negated=True), models.Q(('document_number', ''), _negated=True)), fields=('partner', 'document_type', 'document_number'), name='partners_unique_contact_document'),
        ),
    ]
