# -*- coding: utf-8 -*-
from .common import ArchiveActionSerializer, MonitoringModelSerializer
from .installation_token import MonitoringInstallationTokenCreateSerializer, MonitoringInstallationTokenSerializer, MonitoringInstallationTokenValidateSerializer
from .agent import MonitoringAgentCredentialSerializer, MonitoringAgentHeartbeatSerializer, MonitoringAgentRegistrationSerializer, MonitoringAgentSerializer
from .network import MonitoringNetworkExclusionSerializer, MonitoringNetworkSerializer
from .credential import SNMPCredentialSerializer
from .device import DevicePollingStateSerializer, MonitoredDeviceSerializer
from .readings import AccessoryReadingSerializer, ComponentReadingSerializer, ConsumableReadingSerializer, CounterReadingSerializer, DeviceAlertSerializer, DeviceSnapshotSerializer, JobReadingSerializer, RawOIDReadingSerializer, SnapshotIngestionSerializer, TrayReadingSerializer
from .discovery import DiscoveryHostSerializer, MonitoringDiscoverySerializer
from .profiles import DeviceProfileAssignmentSerializer, SNMPProfileMetricSerializer, SNMPProfileSerializer, SNMPProfileTestMetricSerializer, SNMPProfileTestSerializer
from .agent_operations import AgentCommandLogSerializer, AgentCommandSerializer, AgentLogSerializer, AgentSyncSerializer, DeviceEventSerializer
from .notifications import MonitoringNotificationDeliverySerializer, MonitoringNotificationInstanceSerializer, MonitoringNotificationRuleSerializer, MonitoringReportExecutionSerializer, MonitoringReportScheduleSerializer
from .configuration import AgentConfigurationVersionSerializer, MonitoringConfigurationSerializer, MonitoringDataRetentionPolicySerializer, MonitoringIngestionBatchSerializer

__all__ = [name for name in globals() if name.endswith("Serializer")]
